[build]
  publish = "."
  command = "echo 'Build complete - all platforms ready'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:;"

# Individual platform redirects
[[redirects]]
  from = "/mobile-app/*"
  to = "/mobile-app-platform/:splat"
  status = 200

[[redirects]]
  from = "/youtube/*"
  to = "/youtube-platform/:splat"
  status = 200

[[redirects]]
  from = "/game/*"
  to = "/game-platform/:splat"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/web-dashboard/:splat"
  status = 200

[[redirects]]
  from = "/monetization/*"
  to = "/monetization/:splat"
  status = 200